module.exports = {
    // COMMON
    NO_DATA: 'NO_DATA',

    // TOKEN
    EXPIRED_TOKEN: 'EXPIRED_TOKEN',
    INVALID_TOKEN: 'INVALID_TOKEN',
    MISMATCH_TOKEN: 'MISMATCH_TOKEN',

    NO_AUTHORITY: 'NO_AUTHORITY',
    // USER
    NO_USER: 'NO_USER',
    ALREADY_USER: 'ALREADY_USER',

    // LOCATION
    INVALID_LOCATION: 'INVALID_LOCATION',

    // WEAHTER:
    NO_DAILY_WEATHER: 'NO_DAILY_WEATHER_DATA',

    // WEATHY
    DUPLICATION_WEATHY: 'DUPLICATION_WEATHRY_ERROR',

    // CLOTHES
    ALREADY_CLOTHES: 'ALREADY_CLOTHES',
    NO_CLOTHES: 'NO_CLOTHES',
    NOT_AUTHORIZED_CLOTHES: 'NOT_AUTHORIZED_CLOTHES',

    // REQUEST
    BAD_REQUEST: 'BAD_REQUEST',

    // SERVER
    SERVER_ERROR: 'SERVER_ ERROR'
};
