module.exports = {
    // TOKEN
    EXPIRED_TOKEN: 'EXPIRED_TOKEN',
    INVALID_TOKEN: 'INVALID_TOKEN',
    MISMATCH_TOKEN: 'MISMATCH_TOKEN',

    // USER
    NO_USER: 'NO_USER',

    // CLOTHES
    ALREADY_CLOTHES: 'ALREADY_CLOTHES',

    // REQUEST
    BAD_REQUEST: 'BAD_REQUEST',

    // SERVER
    SERVER_ERROR: 'SERVER_ERROR'
};
